create extension if not exists "pgcrypto";

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  name text not null,
  lecturer text not null,
  room text not null,
  credits integer not null default 3,
  progress integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, code)
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  file_name text not null,
  mime_type text not null,
  file_url text,
  content_text text,
  status text not null check (status in ('uploaded','rewritten','perfected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rewrites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id bigint not null references public.notes(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  body text not null default '',
  word_count integer not null default 0,
  status text not null check (status in ('draft','published','perfected')) default 'draft',
  updated_at timestamptz not null default now(),
  unique(user_id, note_id)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  due_date date not null,
  priority text not null check (priority in ('low','medium','high')) default 'medium',
  status text not null check (status in ('todo','doing','done')) default 'todo',
  note_id bigint references public.notes(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  note_id bigint references public.notes(id) on delete set null,
  duration_minutes integer not null,
  completed_at timestamptz not null default now()
);

alter table public.courses enable row level security;
alter table public.notes enable row level security;
alter table public.focus_sessions enable row level security;
alter table public.rewrites enable row level security;
alter table public.assignments enable row level security;
alter table public.tasks enable row level security;

create policy "users read own courses" on public.courses for select using (auth.uid() = user_id);
create policy "users insert own courses" on public.courses for insert with check (auth.uid() = user_id);
create policy "users update own courses" on public.courses for update using (auth.uid() = user_id);

create policy "users read own notes" on public.notes for select using (auth.uid() = user_id);
create policy "users insert own notes" on public.notes for insert with check (auth.uid() = user_id);
create policy "users update own notes" on public.notes for update using (auth.uid() = user_id);

create policy "users read own rewrites" on public.rewrites for select using (auth.uid() = user_id);
create policy "users insert own rewrites" on public.rewrites for insert with check (auth.uid() = user_id);
create policy "users update own rewrites" on public.rewrites for update using (auth.uid() = user_id);

create policy "users read own assignments" on public.assignments for select using (auth.uid() = user_id);
create policy "users insert own assignments" on public.assignments for insert with check (auth.uid() = user_id);
create policy "users update own assignments" on public.assignments for update using (auth.uid() = user_id);

create policy "users read own tasks" on public.tasks for select using (auth.uid() = user_id);
create policy "users insert own tasks" on public.tasks for insert with check (auth.uid() = user_id);
create policy "users update own tasks" on public.tasks for update using (auth.uid() = user_id);

create policy "users read own focus" on public.focus_sessions for select using (auth.uid() = user_id);
create policy "users insert own focus" on public.focus_sessions for insert with check (auth.uid() = user_id);

create index if not exists idx_courses_user_updated_at on public.courses(user_id, updated_at desc);
create index if not exists idx_notes_user_updated_at on public.notes(user_id, updated_at desc);
create index if not exists idx_rewrites_user_updated_at on public.rewrites(user_id, updated_at desc);
create index if not exists idx_assignments_user_due_date on public.assignments(user_id, due_date);
create index if not exists idx_tasks_user_assignment on public.tasks(user_id, assignment_id);
create index if not exists idx_focus_user_completed_at on public.focus_sessions(user_id, completed_at desc);

insert into storage.buckets (id, name, public)
values ('notes', 'notes', true)
on conflict (id) do nothing;
