create extension if not exists "pgcrypto";

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  name text not null,
  lecturer text not null,
  room text not null,
  credits integer not null default 3,
  progress integer not null default 0,
  created_at timestamptz not null default now(),
  unique(user_id, code)
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  file_name text not null,
  mime_type text not null,
  file_url text,
  content_text text,
  status text not null check (status in ('uploaded','rewritten','perfected')),
  created_at timestamptz not null default now()
);

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  note_id bigint references public.notes(id) on delete set null,
  duration_minutes integer not null,
  completed_at timestamptz not null default now()
);

alter table public.courses enable row level security;
alter table public.notes enable row level security;
alter table public.focus_sessions enable row level security;

create policy "users read own courses" on public.courses for select using (auth.uid() = user_id);
create policy "users insert own courses" on public.courses for insert with check (auth.uid() = user_id);
create policy "users update own courses" on public.courses for update using (auth.uid() = user_id);

create policy "users read own notes" on public.notes for select using (auth.uid() = user_id);
create policy "users insert own notes" on public.notes for insert with check (auth.uid() = user_id);
create policy "users update own notes" on public.notes for update using (auth.uid() = user_id);

create policy "users read own focus" on public.focus_sessions for select using (auth.uid() = user_id);
create policy "users insert own focus" on public.focus_sessions for insert with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('notes', 'notes', true)
on conflict (id) do nothing;
